- hosts: ["3.34.46.247"]
  tasks:
  - name: Update APT package cache
    apt:
      update_cache: yes
    become: yes
  - name: Install Nginx
    apt:
      name: nginx
      state: present
    become: yes
  - name: Start Nginx service
    systemd:
      name: nginx
      state: started
      enabled: yes
  - name: Clone Git repository
    git:
      repo: https://github.com/ddarahakit2023/devops
      dest: /tmp/devops 
    become: yes 
  - name: Move HTML files to /var/www/html
    shell: mv -f /tmp/devops/*.html /var/www/html
    become: yes  